dm_descriptions <- c(
  "Type II diabetes mellitus",                                                                                      
  #"O/E - Right diabetic foot at low risk",  #not include for now                                                                        
  #"Diabetic annual review", #not include for now                                                                                        
  #"O/E - Left diabetic foot at low risk",   #not include for now                                                                        
  #"Diabetic dietary review", #not include for now  
  "Diabetic retinopathy",
  "Diabetes mellitus",   
  "Insulin treated Type 2 diabetes mellitus",                                                                       
  "Background diabetic retinopathy",                                                                                
  "Diabetic on insulin and oral treatment",                                                                         
  #"Diabetic monitoring",   #not include for now                                                                                         
  "Diabetic on oral treatment",                                                                                     
  "Type II diabetic dietary review",                                                                                
  "Diabetic on diet only",                                                                                          
  #"Diabetic diet",   #not include for now                                                                                               
  "Diabetic 6 month review",                                                                                        
  "O/E - left eye background diabetic retinopathy",                                                                 
  #"Follow-up diabetic assessment", #not include for now                                                                                  
  "O/E - Right diabetic foot - ulcerated",                                                                          
  "O/E - Left diabetic foot - ulcerated",                                                                           
  "Diabetic retinopathy",                                                                                           
  "O/E - Right diabetic foot at high risk",                                                                         
  "O/E - Left diabetic foot at moderate risk",                                                                      
  "O/E - Right diabetic foot at moderate risk",                                                                     
  "Diabetic - adequate control",                                                                                    
  "Diabetic - poor control",                                                                                        
  "Diabetic - good control",                                                                                        
  "Insulin dependent diabetes mellitus",                                                                            
  "Type 1 diabetes mellitus",                                                                                       
  "Non-insulin dependent diabetes mellitus",                                                                        
  #"Diabetic - follow-up default",   #not include for now                                                                                
  "Proliferative diabetic retinopathy",                                                                             
  "Type 2 diabetes mellitus",                                                                                       
  "Chronic painful diabetic neuropathy",                                                                            
  "Diabetes mellitus with ketoacidosis",                                                                            
  "Diabetes mellitus with neurological manifestation",                                                              
  "Diabetes mellitus, juvenile type, with no mention of complication",                                              
  "Diabetic maculopathy",                                                                                           
  "Initial diabetic assessment",                                                                                    
  "Conversion to insulin",                                                                                          
  "O/E - right eye background diabetic retinopathy",                                                                
  "Type I diabetes mellitus",                                                                                       
  "O/E - Left diabetic foot at high risk",                                                                          
  "O/E - right eye proliferative diabetic retinopathy",                                                             
  "Type I diabetic dietary review",                                                                                 
  #"Seen in diabetic eye clinic",   #not include for now                                                                                 
  #"Diabetic monitoring NOS",      #not include for now                                                                                  
  "Polyneuropathy in diabetes",                                                                                     
  "Ischaemic ulcer diabetic foot",                                                                                  
  "Type 1 diabetes mellitus with persistent proteinuria",                                                           
  "Neuropathic diabetic ulcer - foot",                                                                              
  "O/E - Left diabetic foot at increased risk",                                                                     
  "O/E - Right diabetic foot at increased risk",                                                                    
  #"Annual diabetic blood test",  #not include for now                                                                                   
  "Diabetic retinopathy NOS",                                                                                       
  "Type I diabetes mellitus without complication",                                                                  
  "Type II diabetes mellitus without complication",                                                                 
  "Diabetes mellitus, adult onset, with no mention of complication",                                                
  "Diabetic neuropathy",                                                                                            
  "O/E - right eye preproliferative diabetic retinopathy",                                                          
  "O/E - diabetic maculopathy present both eyes",                                                                   
  "O/E - Right diabetic foot at risk",                                                                              
  "Diabetes mellitus with ophthalmic manifestation",                                                                
  "O/E - left eye diabetic maculopathy",                                                                            
  "O/E - right eye diabetic maculopathy",                                                                           
  "O/E - Left diabetic foot at risk",                                                                               
  "Diabetic treatment changed",                                                                                     
  "Proteinuric diabetic nephropathy",                                                                               
  "Diabetic mononeuritis NOS",                                                                                      
  "O/E - left eye proliferative diabetic retinopathy",                                                              
  "Hypoglycaemic event in diabetes",                                                                                
  "Type II diabetes mellitus - poor control",                                                                       
  "Mild non proliferative diabetic retinopathy",                                                                    
  "Type II diabetes mellitus with persistent microalbuminuria",                                                     
  "Non-insulin-dependent diabetes mellitus without complication",                                                   
  "Diabetes mellitus (& [ketoacidosis])",                                                                           
  "Moderate non proliferative diabetic retinopathy",                                                                
  "Type II diabetes mellitus with renal complications",                                                             
  "Diabetic ketoacidosis",                                                                                          
  #"Glucose tol. test diabetic",      #not include for now                                                                               
  "Non proliferative diabetic retinopathy",                                                                         
  "Diabetic polyneuropathy",                                                                                        
  #"Diabetic monitoring (& [clinic])",  #not include for now                                                                             
  "Diabetes mellitus autosomal dominant type 2",                                                                    
  "Diabetes mellitus: [adult onset, with no mention of complication] or [maturity onset] or [non-insulin dependent]",
  "Diabetes + neuropathy (& [amyotrophy])",                                                                         
  "O/E - left eye preproliferative diabetic retinopathy",                                                           
  "Diabetic cataract",                                                                                              
  "Type II diabetes mellitus with nephropathy",                                                                     
  "Diabetes mellitus with renal manifestation",                                                                     
  "Diabetes mellitus NOS with ketoacidosis",                                                                        
  "Diabetic - poor control NOS",                                                                                     
  "Type 2 diabetes mellitus - poor control",                                                                        
  #"Admit diabetic emergency",     #not include for now                                                                                  
  "Asymptomatic diabetic neuropathy",                                                                               
  "Preproliferative diabetic retinopathy",                                                                          
  "Type I diabetes mellitus - poor control",                                                                        
  "Type I diabetes mellitus with ophthalmic complications",                                                         
  "Cellulitis in diabetic foot",                                                                                    
  "Diabetic neuropathy &/or diabetic polyneuropathy",                                                                                
  "Symptomatic diabetic peripheral neuropathy",                                                                     
  #"Diabetic care",   #Not include for now                                                                                               
  "Diabetic nephropathy",                                                                                           
  "H/O: diabetes mellitus type 2",                                                                                  
  "Diabetic macular oedema",                                                                                            
  "Type II diabetes mellitus with ophthalmic complications",                                                        
  "Proliferative diabetic retinopathy - high risk",                                                                 
  "Type 2 diabetes mellitus with neuropathic arthropathy",                                                          
  #"Nocturnal hypoglycaemia",   #not include for now                                                                                     
  #"Diabetic on subcutaneous treatment", #not include for now                                                                            
  "Unstable type I diabetes mellitus",                                                                              
  "Date diabetic treatment start",                                                                                  
  "Diabetes mellitus: [with renal manifestation] or [nephropathy]",                                                 
  "Diabetes mellitus autosomal dominant",                                                                           
  "Type 2 diabetes mellitus with persistent proteinuria",                                                           
  "Diabetes mellitus NOS with no mention of complication",                                                          
  "Type II diabetes mellitus with polyneuropathy",                                                                  
  "O/E - right eye stable treated proliferative diabetic retinopathy",                                              
  "O/E - left eye stable treated proliferative diabetic retinopathy",                                                                             
  "Diabetic autonomic neuropathy",                                                                                  
  "Diabetes mellitus with hyperosmolar coma",                                                                       
  "Hyperosmolar non-ketotic state in type 2 diabetes mellitus",                                                     
  "Type II diabetes mellitus with exudative maculopathy",                                                                                        
  "Diabetic - cooperative patient",                                                                                 
  "Diabetes mellitus with no mention of complication",                                                              
  "Type II diabetes mellitus with diabetic cataract",                                                               
  "Diabetic hand syndrome",                                                                                         
  "[D]Gangrene of toe in diabetic",                                                                                 
  "Diabetes mellitus: [juvenile type, with no mention of complication] or [insulin dependent]",                     
  "Type II diabetes mellitus with retinopathy",                                                                     
  "Diabetes mellitus NOS with ketoacidotic coma",                                                                   
  "Advanced diabetic maculopathy",                                                                          
  "Diabetes mellitus: [adult onset] or [noninsulin dependent]",                                                     
  "Diabetes mellitus with peripheral circulatory disorder",                                                         
  # "Chronic hyperglycaemia", #no include for now                                                                                        
  "Mixed diabetic ulcer - foot",                                                                                    
  "Type I diabetes mellitus with retinopathy",                                                                      
  "Diabetes mellitus with persistent proteinuria",                                                                  
  "Diabetic mononeuropathy",                                                                                        
  "Type 2 diabetes mellitus with persistent microalbuminuria",                                                                        
  "Type II diabetes mellitus with persistent proteinuria",                                                          
  "Diabetes mellitus with neurological manifestation: (& [amyotrophy] or [neuropathy] or [polyneuropathy])",        
  "Autonomic neuropathy due to diabetes",                                                                           
  "Type 2 diabetes mellitus with nephropathy",                                                                      
  "Diabetic retinopathy detected by national screening programme",                                                  
  "Diabetic neuropathic arthropathy",                                                                               
  "Proliferative diabetic retinopathy with new vessels elsewhere than on disc",                                     
  "Diabetes mellitus with unspecified complication",                                                                
  "Secondary pancreatic diabetes mellitus",                                                                         
  "Diabetes + eye manifestation (& [cataract] or [retinopathy])",                                                   
  "Visually threatening diabetic retinopathy",                                                                      
  "Hypoglycaemic state in diabetes",                                                                                
  "Diabetes mellitus with persistent microalbuminuria",                                                             
  "Acute painful diabetic neuropathy",                                                                              
  #"Suspected diabetes mellitus", #not include                                                                                  
  #"No symptomatic diabetic peripheral neuropathy",   #not include                                                               
  "Diabetic foot",                                                                                                  
  "Type II diabetes mellitus with neurological complications",                                                      
  "Diabetic amyotrophy",                                                                                            
  "Maternally inherited diabetes mellitus",                                                                         
  "Type 2 diabetes mellitus with retinopathy",                                                                      
  "See X40J5",  #Type II                                                                                                    
  "Type 1 diabetes mellitus with gastroparesis",                                                                    
  "Diabetic iritis",                                                                                                
  "Type I diabetes mellitus maturity onset",                                                                        
  "Diabetes mellitus NOS with ophthalmic manifestation",                                                            
  "Diabetes mellitus with ketoacidotic coma",                                                                       
  "Type I diabetes mellitus with renal complications",                                                              
  "Diabetes mellitus NOS with neurological manifestation",                                                          
  "Diabetic - poor control (& unstable)",                                                                           
  "Type 2 diabetes mellitus without complication",                                                                  
  "Other specified diabetes mellitus with ketoacidosis",                                                            
  "O/E - sight threatening diabetic retinopathy",                                                                   
  "Mixed diabetic maculopathy",                                                                                     
  "Diabetic vitreous haemorrhage",                                                                                  
  "Type I diabetes mellitus with hypoglycaemic coma",                                                               
  "Diabetic treatment changed (& [date])",                                                                          
  "Type II diabetes mellitus with mononeuropathy",                                                                  
  "Severe non proliferative diabetic retinopathy",                                                                  
  "Type 2 diabetes mellitus with exudative maculopathy",                                                            
  "Type II diabetes mellitus with ulcer",                                                                           
  "Ischaemic diabetic maculopathy",                                                                                 
  "Type II diabetes mellitus with multiple complications",                                                          
  "Insulin dependent diabetes maturity onset",                                                                      
  "Diabetic severe hyperglycaemia",                                                                                 
  "Type 1 diabetes mellitus with nephropathy",                                                                      
  "Type 2 diabetes mellitus with diabetic cataract",                                                                
  "Diabetes mellitus, adult onset, with neurological manifestation",                                                
  #"Non-urgent diabetic admission",       #not include for now                                                                           
  "Type 1 diabetes mellitus with retinopathy",                                                                      
  "Diabetic dermopathy",                                                                                            
  "Diabetes mellitus, adult onset, with renal manifestation",                                                       
  "O/E - left chronic diabetic foot ulcer",                                                                         
  "Type 1 diabetes mellitus with persistent microalbuminuria",                                                      
  "Diabetic cheiroarthropathy",                                                                                     
  "Diabetes mellitus NOS with other specified manifestation",                                                       
  "Type 1 diabetes mellitus with exudative maculopathy",                                                            
  "Diabetes: [peripheral circulatory disease] or [gangrene]",                                                       
  "Diabetic peripheral angiopathy",                                                                 
  "Non-insulin dependent diabetes mellitus - poor control",                                                         
  #"Latent autoimmune diabetes mellitus in adult",    #not include for now                                                               
  "Type 2 diabetes mellitus with polyneuropathy",                                                                          
  "Other specified diabetes mellitus with neurological complications",                                              
  "Insulin dependent diabetes mellitus - poor control",                                                             
  "Type 2 diabetes mellitus with gastroparesis",                                                                    
  "Maturity onset diabetes mellitus in young",                                                                      
  "Type 2 diabetes mellitus with ketoacidosis",                                                                     
  "Diabetic Charcot arthropathy",                                                                                   
  "Type I diabetes mellitus with nephropathy",                                                                      
  "Diffuse diabetic glomerulosclerosis",                                                                            
  "Diabetic necrobiosis lipoidica",                                                                                 
  "Type 1 diabetes mellitus with diabetic cataract",                                                                
  "Focal diabetic maculopathy",                                                                                     
  "Diabetic distal sensorimotor polyneuropathy",                                                                    
  "Type I diabetes mellitus with arthropathy",                                                                      
  "Diabetes mellitus, juvenile type, with neurological manifestation",                                              
  "Type I diabetes mellitus with ulcer",                                                                            
  "Type 1 diabetes mellitus with arthropathy",                                                                      
  "Microalbuminuric diabetic nephropathy",                                                                          
  "Type II diabetes mellitus with arthropathy",                                                                     
  "Type 2 diabetes mellitus with renal complications",                                                              
  "Diabetes mellitus with nephropathy NOS",                                                                         
  "Diabetic-uncooperative patient",                                                                                 
  "Type 1 diabetes mellitus with ketoacidosis",                                                                     
  #"Myasthenic syndrome due to diabetic amyotrophy",   #not include for now                                                              
  "Type I diabetes mellitus with multiple complications",                                                           
  "Type I diabetes mellitus with polyneuropathy",                                                                   
  "Type I diabetes mellitus with diabetic cataract",                                                                
  "High risk non proliferative diabetic retinopathy",                                                               
  "Diabetic on insulin and glucagon-like peptide 1 receptor agonist",                                               
  "Antidiabetic agent",                                                                                             
  #"Diabetic monitoring - lower risk albumin excretion",#not include for now                                                             
  "(Secondary cataract) or (diabetic cataract)",  #not include for now                                                                  
  "Diabetic coma",                                                                                                  
  "Diabetic chronic painful polyneuropathy",                                                                        
  "Type 1 diabetes mellitus with ketoacidotic coma",                                                                
  "Recurrent severe hypoglycaemia",    #not include for now                                                          
  "Type 1 diabetes mellitus - poor control",                                                                        
  "Type II diabetes mellitus with hypoglycaemic coma",                                                              
  "Diabetes mellitus, adult onset, with ophthalmic manifestation",                                                                                  
  "Advanced diabetic retinal disease",                                                                              
  "Diabetic mononeuritis multiplex",                                                                                
  "Non-insulin dependent diabetes mellitus with nephropathy",
  "Type II diabetes mellitus",
  #"Insulin autoimmune syndrome", #not include for now                                                                                   
  "O/E - right chronic diabetic foot ulcer",
  # "Seen in diabetic clinic",                                                                          
  # "Pt advised re diabetic diet",                                                                     
  # "Dietary advice for diabetes mellitus",                                                            
  # "Diabetic dietary review",                                                                         
  "Diabetes management plan given",                                                                  
  #  "Diabetic monitoring",                                                                             
  #  "[V]Dietary surveillance and counselling",                                                         
  # "Diabetes monitoring admin.NOS",                                                                   
  # "Injection sites",                                                                                 
  # "Dietary advice for type II diabetes",                                                             
  # "Diabetic weight reducing diet",                                                                   
  # "Diabetic retinopathy screening",                                                                  
  "H/O: diabetes mellitus",                                                                          
  # "Diabetes monitoring admin.",                                                                      
  "Diabetic on insulin",                                                                             
  # "Diabetic annual review",                                                                          
  # "O/E - Right diabetic foot at low risk",                                                           
  # "O/E - Left diabetic foot at low risk",                                                            
  # "Diabetic lipid lowering diet",                                                                    
  # "Diabetes: practice programme",                                                                    
  "Diabetic monitoring - injection sites",                                                           
  # "Diabetic diet - good compliance",                                                                 
  # "Seen in diabetic eye clinic",                                                                     
  # "Fundoscopy - diabetic check",                                                                     
  # "Diabetic diet",                                                                                   
  "Diabetes medication review",                                                                      
  "Diabetes care plan agreed",                                                                       
  # "Has seen dietician - diabetes",                                                                   
  # "Refer to diabetic foot screener",                                                                 
  "Diabetes type 2 review",                                                                          
  # "Diabetes monitor. check done",                                                                    
  # "Understands diet - diabetes",                                                                     
  # "Follow-up diabetic assessment",                                                                   
  # "Diabetic foot screen",                                                                            
  # "Diabetic Clinic",                                                                                 
  # "Attending diabetes clinic",                                                                       
  "Pre-existing diabetes mellitus, unspecified",                                                     
  "Non-insulin-dependent diabetes mellitus with retinopathy",                                        
  # "Diabetes: shared care programme",                                                                 
  "Retinal abnormality - diabetes-related",                                                          
  "Type II diabetes on diet only",                                                                   
  # "Diabetic monitoring NOS",                                                                         
  "Diabetic erectile dysfunction review",                                                            
  # "Specific advice for diabetics",                                                                   
  # "Attends diabetes monitoring",                                                                     
  "Insulin passport given",                                                                          
  # "Diabetic peripheral neuropathy screening",                                                        
  # "Glucose tol. test diabetic",                                                                      
  # "Annual diabetic blood test",                                                                      
  #"Admission to diabetic department",                                                                
  # "Diabetes Year of Care annual review",                                                             
  # "Pre-conception advice for diabetes mellitus",                                                     
  # "Seen in community diabetes specialist clinic",                                                    
  # "Refer, diabetic liaison nurse",                                                                   
  # "Diabetes monitoring status",                                                                      
  "Diabetic retinopathy 6 month review",                                                             
  "[X]Insulin and oral hypoglycaemic [antidiabetic] drugs causing adverse effects in therapeutic use",
  # "Seen in multidisciplinary diabetic clinic",                                                       
  "Diabetic retinopathy 12 month review",                                                            
  # "Diabetes monitoring check done",                                                                  
  # "Patient held diabetic record issued",                                                             
  # "Diabetic foot risk assessment",                                                                   
  "Diabetes type II review",                                                                         
  # "Diabetic - follow-up default",                                                                    
  "Diabetic medicine",                                                                               
  "Diabetic assessment of erectile dysfunction",                                                     
  # "Diabetes Obesity Clinic",                                                                         
  # "Seen in diabetic foot clinic",                                                                    
  "H/O: insulin therapy",                                                                            
  # "Diabetes monitoring call",                                                                        
  # "Diabetes care by hospital only",                                                                  
  #"Insulin resistance",                                                                              
  "Subcutaneous injection of insulin",                                                               
  # "Diabetic review",                                                                                 
  "Diabetes self-management plan review",                                                            
  # "Seen in diabetic nurse consultant clinic",                                                        
  # "Diabetes clinic administration",                                                                  
  # "Patient consent given for addition to diabetic register",                                         
  "Type II diabetes on insulin",                                                                     
  "Diabetic drug side effects",                                                                      
  "Diabetic diet - poor compliance",                                                                 
  "Brittle diabetes",                                                                                
  "Patient on maximal tolerated therapy for diabetes",                                               
  # "Functional hyperinsulinism",                                                                      
  "Diabetic hyperosmolar non-ketotic state",                                                         
  "Erectile dysfunction due to diabetes mellitus",                                                   
  "Pan retinal photocoagulation for diabetes",                                                       
  "Diabetes self-management plan agreed",                                                            
  # "Diabetic retinopathy screening administrative status",                                            
  "Insulin lipohypertrophy",                                                                         
  "Diabetes clinical management plan",                                                               
  "(Secondary cataract) or (diabetic cataract)",                                                     
  # "Insulin level",                                                                                   
  # "Wolcott-Rallison dysplasia",                                                                      
  "Hypoglycaemic coma"                                                                              
  # "Diabetes monitoring default",                                                                     
  # "Latent autoimmune diabetes mellitus in adult",
)
